spring:
   application:
      name: ToDoConfigServer
   cloud:
      config:
             server:
                 git:
                       uri: https://github.com/Medinipd627/ConfigFile.git
server:
     port: 8888
    